* Usage
1. Click on stuff, edit fields, make selections.
2. Click the green check. There is no property writing, cutlist updating, &c. until the you click the green check.
* Inserting into the cutlist DB
For reasons in the footnotes, don't create cutlists from models in the development directory. The world won't end, but it would be mildly annoying later.
** From the model view to an existing cutlist
1. Select the part to be inserted.
2. Set the =Quantity= spinner appropriately.
3. Click =Insert Into Cutlist=.
   If this part exists in the database, but is now in a new location, Mr Redbrick will ask if you want to make this new part a primary part[[https://github.com/kcjuntunen/Redbrick-Addin/wiki#footnotes][¹]].
4. When Mr Redbrick asks whether you want to add the part to an existing cutlist, say "Yes".
5. Mr Redbrick will guess (based on the last cutlist you were fooling around with) just which existing cutlist you want to insert into. All the fields on the window will be populated from existing cutlist data. If you like what's in there, leave it. If not, pick a different cutlist. I don't care. You can even change the automatically populated fields if you want them changed.
6. Click =Add=.
7. With all your extra time, watch [[https://www.youtube.com/watch?v=Wga5A6R9BJg][this funny video]].
** From the model view to a new cutlist
1. Select the part to be inserted.
2. Set the =Quantity= spinner appropriately.
3. Click =Insert Into Cutlist=.
   If this part exists in the database, but is now in a new location, Mr Redbrick will ask if you want to make this new part a primary part[[https://github.com/kcjuntunen/Redbrick-Addin/wiki#footnotes][¹]].
4. When Mr Redbrick asks whether you want to add the part to an existing cutlist, say "No".
5. The cutlist creation box will pop up with only the date, and your name filled in. You'll have to do the rest; Mr Redbrick can't read your mind!
6. Click =Create Cutlist=.
7. Meditate on how quick that really was: two clicks, a little typing, and one click.
** From the drawing view
1. Insert a BOM. (There's a template located at =G:\Solid Works\AMSTORE CUTLIST BOM\CL.sldbomtbt=)
   The order of columns doesn't matter; move them around if you like.
2. Select the BOM, or don't. With the BOM selected, you can manually select the correct BOM. But, without a a selection, the Redbrick will attempt to find the BOM, itself.
3. Click =Create/Update=.
4. The Redbrick will attempt to determine the customer from drawing properties. The =ItemNumber=, and =Drawing Reference= fields will be populated from the =Item #=.
   If the cutlist already exists, it will be updated, otherwise it is created.
5. Click =Create=.
6. Feel satisfied; the cutlist is set up under your name with a status of =STARTED=.
* Secret trick
The labels for the combo-boxes also copy combo-box content to the clipboard.

Currently copy-clickable fields include:
- =Cutlist Material=
- =Edge Front (L)=
- =Edge Back (L)=
- =Edge Left (W)=
- =Edge Right (W)=
- The partnumber just under the green checkmark is also copy-clickable.
* Troubleshooting
If it quits refreshing for some reason, hit the refresh icon. That usually fixes it. I'm working on it.
In the worst case, 
1. Go to =Tools= → =Addins...=.
2. Uncheck the Redbrick.
3. Click =OK=.
4. Go to =Tools= → =Addins...=.
5. Re-check the Redbrick.
6. Click =OK=.

You're probably all set now.

* Code I'm borrowing
- Crc32.cs unchanged from [[https://github.com/damieng/DamienGKit.git][Damien Guard's DamienGKit]] under Apache License v2.0.

* Footnotes

 ¹The Redbrick is now aware of whether a part is primary or not. This functionality is based on the part's file location. If a part is not primary, its properties can be set in the Redbrick, but they won't carry all the way through to the Cutlist DB.
