//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbrick_Addin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Redbrick_Addin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add {0} to an existing cutlist?.
        /// </summary>
        internal static string AddToExistingCutlist {
            get {
                return ResourceManager.GetString("AddToExistingCutlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This part ({0}) was renamed, or already exists in another location. Override?.
        /// </summary>
        internal static string AlreadyInOtherLocation {
            get {
                return ResourceManager.GetString("AlreadyInOtherLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • .
        /// </summary>
        internal static string Bullet {
            get {
                return ResourceManager.GetString("Bullet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot be longer than 35 characters. Cutlist will fail to upload..
        /// </summary>
        internal static string CheckDescrLength {
            get {
                return ResourceManager.GetString("CheckDescrLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CNC op between {0} and {1}; check overzise values..
        /// </summary>
        internal static string CheckOversize {
            get {
                return ResourceManager.GetString("CheckOversize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part number cannot be longer than 25 characters. Cutlist will fail to upload..
        /// </summary>
        internal static string CheckPartnumLength {
            get {
                return ResourceManager.GetString("CheckPartnumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clipboard {
            get {
                object obj = ResourceManager.GetObject("clipboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the Customer box..
        /// </summary>
        internal static string CustomerEmpty {
            get {
                return ResourceManager.GetString("CustomerEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Description cannot be greater than 40 characters long. Cannot upload cutlist..
        /// </summary>
        internal static string CutlistDescriptionTooLong {
            get {
                return ResourceManager.GetString("CutlistDescriptionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutlist not selected. Only global properties have been updated..
        /// </summary>
        internal static string CutlistNotSelected {
            get {
                return ResourceManager.GetString("CutlistNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Cutlist.
        /// </summary>
        internal static string InsertIntoCutlistButtonText {
            get {
                return ResourceManager.GetString("InsertIntoCutlistButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert &apos;{0}&apos; into ECR# {1} items?.
        /// </summary>
        internal static string InsertIntoEcrItems {
            get {
                return ResourceManager.GetString("InsertIntoEcrItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the Item Number box..
        /// </summary>
        internal static string ItemNumberEmpty {
            get {
                return ResourceManager.GetString("ItemNumberEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Into Cutlist.
        /// </summary>
        internal static string MakeOriginalButtonText {
            get {
                return ResourceManager.GetString("MakeOriginalButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to save your property changes?.
        /// </summary>
        internal static string MaybeSave {
            get {
                return ResourceManager.GetString("MaybeSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A SolidWorks document must be open..
        /// </summary>
        internal static string MustOpenDocument {
            get {
                return ResourceManager.GetString("MustOpenDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessary network resources are not available. Redbrick not starting..
        /// </summary>
        internal static string NetworkNotAvailable {
            get {
                return ResourceManager.GetString("NetworkNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EB Op inconsistent with banding..
        /// </summary>
        internal static string NoEBWarning {
            get {
                return ResourceManager.GetString("NoEBWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNC Op inconsistent with CNC programs..
        /// </summary>
        internal static string NoProgramWarning {
            get {
                return ResourceManager.GetString("NoProgramWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap redlego {
            get {
                object obj = ResourceManager.GetObject("redlego", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll have to restart SolidWorks to see any effect..
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap setup {
            get {
                object obj = ResourceManager.GetObject("setup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Editor {0}.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version of the  Property Editor is out of date.   Do you want to update from {0} to {1}?.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update from {0} to {1}?.
        /// </summary>
        internal static string UpdateFrom {
            get {
                return ResourceManager.GetString("UpdateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE: Fixed update checkbox..
        /// </summary>
        internal static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some dimension(s) resolved to a value of 0.000..
        /// </summary>
        internal static string ZeroValueDimension {
            get {
                return ResourceManager.GetString("ZeroValueDimension", resourceCulture);
            }
        }
    }
}
